### ISSUE TITLE
Remove user data hosted in public repo

### ISSUE THREAD

**Issue by Cosmopal** [NKShukla/IIITD_Sports_Management_System#2]
Hi,
Looks like you've hosted names, genders and email addresses of about 250 IIITD students in a file of this repository. 
I think that should be removed.

**Comment by Cosmopal** [comment]
Specifically, this file - https://github.com/NKShukla/IIITD_Sports_Management_System/blob/716d09db52c723b45fdc67bd3928c21f2dc72c86/sql_dump/sports_management_person.sql

**Comment by NKShukla** [comment]
Hi Palash,

So we basically used the college website (https://www.iiitd.ac.in/people/btech) to get the students' names which are publicly available and then generated the emails (in IIITD format) using excel. 

We have actually manipulated the batch year, email, gender, etc as per our need. So even though some emails will match with the actual ones, most of them won't.

All other confidential data like a phone number that we have used are fake (randomly generated), because of which we didn't use pseudonymization.

Hope this clarifies the concern.

**Comment by NKShukla** [comment]
I'll add the source website (https://www.iiitd.ac.in/people/btech) in the readme as well

**Comment by virresh** [comment]
@NKShukla 
Pls comply
The passwords are plaintext as well [even though randomly generated]
By no stretch of imagination this data is extremely sensitive and needs to be taken out of public domain

**Comment by virresh** [comment]
I think it's more of a course project than the actual system hosted, wouldn't it suffice to have fake emails, fake names and fake everything for your purposes?

**Comment by NKShukla** [comment]
@viresh I would like to clarify a few things here:

1) It's just a course project and not an actual website that IIITD students are using. And the course was about Database Management and not about Security. Therefore we kept the passwords without any encryption.
2) We have used the actual student names, and IIITD formatted emails just for the sole purpose that it looks relatable, especially to the IIITD folks. Since that information was already publicly available we did not see why we can't use it.

**Comment by Cosmopal** [comment]
@NKShukla 
_Since that information was already publicly available we did not see why we can't use it._
Nope, it wasn't

1. The site only mentions name, roll number, batch and program. You've constructed emails out of those. Thus you've given any spammer in the world an understanding of generating emails of all iiitd students.
2. I don't see gender mentioned on the website, how did you get that?

**Comment by Cosmopal** [comment]
It is generally bad practice to have real people's data as sample data. Especially in a publicly hosted repo.

**Comment by NKShukla** [comment]
@Cosmopal 

1. The only data that we have used are the names and the mailing format. The gender we have added randomly because we needed to manipulate it as per our need.
2. About the mailing format: Even the emails of many students and faculty are out there on the public websites (  https://www.iiitd.ac.in/life/sportscouncil, http://studentcouncil.iiitd.edu.in/representatives.html just to mention a few). So, if any spammer in the world wants to spam, they could do so very easily.

**Comment by virresh** [comment]
> And the course was about Database Management and not about Security. Therefore we kept the passwords without any encryption.

Fair enough. And it's good to see that you're confident in putting out a course project. but the search results are now indexed. Two people were able to reach this repository while searching for something from a search engine. It's safe to assume many others can (and probably will).

> 2. We have used the actual student names, and IIITD formatted emails just for the sole purpose that it looks relatable, especially to the IIITD folks. Since that information was already publicly available we did not see why we can't use it.

Apart from what Cosmopal mentioned, and best practices aside, there are many safe practices that will be helpful for an awesome demo. Not to nag any further, but security is kinda a collective effort from all, and minimizing attack surfaces is in best interest of everyone involved. Github is indexed by way more websites than the one's you mentioned. Rest is upto your good judgement.

**Comment by NKShukla** [comment]
@virresh @Cosmopal 

Thanks for the suggestions. We will discuss it among ourselves, and do the required changes.

**Comment by Cosmopal** [comment]
@NKShukla Hard to believe that genders are randomly generated. I checked the first 20-30 occurrences of 'Male' and 'Female' and they are all associated correctly (i.e. male student names have 'Male' tag and female student names have 'female' tags). This is not possible if you used a random generator. Looks like you've either fetched that info from somewhere or this has been manually annotated.

It's hard to overstate the importance of user data privacy and consent in these days. Even though the emails are deducible, it's not okay to serve that information on a platter.

Looks like you're from class of 2023. If you get a chance, do take the courses offered in IIITD about data privacy to get more info :)

As @virresh said, please don't misunderstand, we're not trying to nag here. We're both already graduated and genuinely wish you good luck for your life at IIITD.
